version: "3"

services:
  jekyll:
    build: .
    image: "0x57/jekyll"
    volumes:
      - ./docs/:/docs/
    ports:
      - "4000:4000"
      - "35729:35729"
    command: bundle exec jekyll serve --livereload --host 0.0.0.0
