source "https://rubygems.org"

gem "jekyll", "~> 4.1.0"
gem "minima", "~> 2.5.1"

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.13"
  gem "jekyll-sitemap", "~> 1.4"
  gem "jekyll-compose", "~> 0.12.0"
  gem "jekyll-postfiles", "~> 3.1"
end

gem "webrick", "~> 1.7"
gem "addressable", "~> 2.8.1"
gem "i18n", "~> 1.12"
gem "liquid", "~> 4.0.4"
gem "public_suffix", "~> 5.0.0"
gem "concurrent-ruby", "~> 1.1.10"
gem "listen", "~> 3.7.1"

